### PR TITLE
Support for Elasticsearch 7.

### LINKED ISSUE #86: Support ElasticSearch 7.0.0

### PR DESCRIPTION
**Pull request by danderson**
This is an attempt to fix #86. There are a number of challenges with this new version:
- [x] The download filenames have changed, and require detecting the OS and supporting tarballs.
- [x] Indexes only support 1 document type now, so all indexing and template logic has to reject invalid index configs, and change the wire format.
- [ ] Routing during indexing no longer works the same way, the way the test framework does it has been deprecated and removed.

The last part is the only piece that doesn't work. All the test pass except for "should index a document using specified routing", which fails because the `_routing` metadata key has been removed, and now you can only specify per-document routing inline inside the document. I wasn't sure how to make that work while preserving compatibility with other versions.

That brings me to something else... Compatibility. This library supports 3 major versions of Elasticsearch, 4 with this PR. Elastic very aggressively breaks APIs and compat between major versions, so I had to hack a lot of "oh this is ES7, do something different" into things. I don't think this library format is sustainable for much longer.

I think it would be better to switch to using major versions as well, and following the Elasticsearch major versions: embedded-elastic 6.x supports ES 6.x, embedded-elastic 7.x supports 7.x, ... That way the API can stick to exactly what each version can do, instead of doing the increasingly difficult job of pleasing all of them at once. WDYT?

I think for ES7 the current approach still works, but ES8 will probably break things even more.

### CODE REVIEW

**Comment by botismarius** [comment]
I also think it would be better to use major versions as well and follow the Elasticsearch major versions.

**Comment by xtermi2** [comment]
Is there any progress in this PR / supporting Elasticsearch 7?

**Comment by xtermi2** [comment]
I now switched for a bunch of projects from embedded-elasticsearch to [testcontainers.org](https://www.testcontainers.org/modules/elasticsearch/), which is working quite well for my purpose. With that solution I don't have to rely on a not so good maintained project like embedded-elasticsearch.
Sorry, but I say goodbye now.

**Comment by petrkalivoda** [comment]
Hi, what exactly (apart from the failing test) is blocking this PR from being accepted? I'll gladly contribute some time to make it work...

**Comment by imochurad** [comment]
why is this PR not merged yet? Can anyone shed some light?

**Comment by danderson** [comment]
The last update to this library was almost a year ago based on git commit timestamps, so it's fairly clear that this is abandoned :(. Closing this PR, because it keeps generating github pings to me when people discover it and comment.

**Pull request closed without merging**
