### PR TITLE
allow user to select JRE to run elasticsearch in

### LINKED ISSUE #70: When running on a system with recent JDK set to default, elasticsearch won't start
I have this Java 8 application which has a couple of Tests using the embedded elasticserch. But, on my computer Java 11 is set to be the default.

When starting the tests, the elasticsearch startup script will fall back to the systems default, without giving me a chance to change this behavior. 

Unfortunately, the elasticsearch version I need to test against is NOT compatible with Java 11, and I don't want to change my systems default behavior.

I suggest adding a configuration parameter to the builder in EmbeddedElastic, say `jreHomeToUse` with the option to have it auto-set to the version of the running tests, not setting at all (and using system default) or setting to an explicit path.

### PR DESCRIPTION
**Pull request by madmuffin1**
this does not break previous behavior as the default remains to rely on
the system default jre

fixes #70

### CODE REVIEW

**Comment by gaczm** [comment]
Hi @madmuffin1 
Code looks ok, but please add some description of this functionality to README

**Comment by madmuffin1** [comment]
> please add some description of this functionality to README
done

**Comment by madmuffin1** [comment]
@gaczm do you have any more remarks?

**Comment by gaczm** [comment]
@madmuffin1 sorry, I forgot completely about your change :/ It looks ok for me. I will release it tomorow

**Pull request merged**
