### PR TITLE
Feature/port management

### PR DESCRIPTION
**Pull request by nnegativ**
Currently the port for Elasticsearch is mandatory and fixed. Because sometimes tests are run on CI server when multiple instances can be built at the same time. Better solution is leave port management to Elasticsearch.

In this PR user can force the particular port (as in current version) or omit the port definition.
The EmbeddedElastic.createClient() adapts to the situation.

Note change the name of method from withPortNumber() to withForcedPortNumber()

### CODE REVIEW

**Comment by gaczm** [comment]
Do you really need that? Usually you specify connection data to your elasticsearch or some other DB in your resources and they must be exactly as specified, so it's not enough that createClient() method adapts to this new situation. And as far as I know builds on CI servers are separated, so you shouldn't have problem with conflicting ports...

**Comment by nnegativ** [comment]
In my situation some builds can be run at the same time and some integration tests may conflict if run on the same ES server. Of cause each job may have some additional configuration for this, but it is not convenient. In my current code I have connection factory which in testing environment create embedded Node. Unfortunately support for this was reduced in ES 2.x and removed in 5.x so I'm trying to find something similar.

**Comment by nnegativ** [comment]
This PR is not complete for another reason. I forgot about cluster.name (my current libraty forms cluster only in particular JVM). So I can do some changes in PR like autogenerating cluster names.

The main question is how it is connected with your vision of this library. I guess my use case is embedded elastic as part of testing framework after changes in ES5

**Comment by gaczm** [comment]
In version 2.0.0 (branch 2.x) I've resigned from setting default port number and cluster name (I've even removed methods for setting them, now there is only withSetting method and some constants representing commonly used settings). So partially it will work as you want. I can add posibility to get used transport/http port numbers from EmbeddedElastic if it's important to you. As to generation of cluster name it can be easily done outside EmbeddedElastic, isn't it?

**Comment by nnegativ** [comment]
Nice. 

You're right about cluster name. On the other hand I think that some redundancy in the API is not bad. For example of course http port can be set using withSetting() but it is not obvious for less experienced users of Elasticsearch.

Another case is remove createClient() - again I can create local client but I need some support from EmbeddedElastic (cluster name and server port maybe also IP address if not local).

The last think: I'm not sure if it is a good idea, but elastic has library for REST communication. Currently is not extended and low level, but using it instead of http commons directly may result in the future (when Transport client will be deprecated).

**Comment by gaczm** [comment]
I don't want to add auto generated cluster names. It's not needed in most scenarios and can be easily done outside.
Examples how to set port number are at the top of README, so it should be relatievly easy to find :) But ok, we can also have methods for that. I have to think about it.
As to removal of createClient and rest client from elastic package. I want to have support for both 2.x and 5.x so I cannot add dependency to elasticsearch libraries. And as for now, there are relatively small number of operation that we do on elasticsearch, so our own, custom rest client is not a pain.
BTW, as for now I have different problem. For unknown reason Travis kills elasticsearch in version 5 spawn in tests. It doesn't do so with version 2.x. It fails on my branch and in two forks that updates dependencies to support only 5.x version. Untill I chase that problem I cannot realease new version :|

**Comment by nnegativ** [comment]
Ok, I have an idea to manage createClient() but it require possibility of getting current ip/port from EmbeddedElastic. I can prepare PR if you want. 

About the problem with travis - something interesting in logs? ES5 do some additional checks during startup and probably require additional memory comparing to ES2

**Comment by gaczm** [comment]
IP is not needed, it is always localhost. I will add methods returning transport/http ports. Only interesting thing is that it is killed by kill -9. No additional logs are present. I will continue investigation tomorrow.

**Comment by nnegativ** [comment]
IP is always localhost unless you use something like:  .withSetting("network.host", "_eth0_")  :)

About kill -9.  OOM killer?

**Comment by gaczm** [comment]
Ok, it works now. Elasticsearch 2.x have memory defaults: -Xms128 -Xmx1g, from 5.0.0 they are -Xms2g -Xms2g; I've added possibility to set ES_JAVA_OPTS variable and set it xms and xmx to smaller values in tests.

I've added getTransportTcpPort and getHttpPort methods. If you change cluster name and host you know to which values you changed them, so you can use those values also when creating cluster. Is that enough for you?

**Comment by nnegativ** [comment]
Thank you for getXXXPort() methods. Just for clarification IP can be set as special values pointing to network interfaces or "any ip non-local address". We can skip this feature now, for my current case localhost is good enough :)

**Pull request closed without merging**
